project: my_project_1

dataset:
  name: cifar10
  dir: ./data
  batch_size: 64
  channels: 3
  height: 32
  width: 32
  output_classes: 10

model:
  name: cnnforcifar10
  optimizer: sgd
  momentum: 0.9
  weight_decay: 0.0005
  lr: 0.001
  criterion: cross_entropy
  epochs: 20

